# Generated by Django 5.1.2 on 2024-11-01 06:13

from django.db import migrations, models

### Dohoon
class Migration(migrations.Migration):

    dependencies = [
        ('app_NUGURI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description_url',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='No description available'),
        ),
    ]
