# Generated by Django 5.1.2 on 2024-11-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_NUGURI', '0003_remove_product_image_url_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='original_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
